name: release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"


jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.70.0
          default: true

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            target/
            ~/.cargo
          key: ${{ runner.os }}-rust

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

      - uses: actions/upload-artifact@v3
        with:
          name: solana-simulator-simulate-linux-x86_64
          path: target/release/simulate

      - uses: actions/upload-artifact@v3
        with:
          name: solana-simulator-get-program-data-linux-x86_64
          path: target/release/get_program_data

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.70.0
          default: true

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            target/
            ~/.cargo
          key: ${{ runner.os }}-rust

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

      - uses: actions/upload-artifact@v3
        with:
          name: solana-simulator-simulate-darwin-x86_64
          path: target/release/simulate
      - uses: actions/upload-artifact@v3
        with:
          name: solana-simulator-get-program-data-darwin-x86_64
          path: target/release/get_program_data

  release:
    needs: [macos, linux]
    runs-on: ubuntu-latest
    steps:
      - name: Get version from tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - uses: actions/download-artifact@v3
        with:
          name: solana-simulator-simulate-darwin-x86_64
          path: bins
      - uses: actions/download-artifact@v3
        with:
          name: solana-simulator-get-program-data-darwin-x86_64
          path: bins
      - uses: actions/download-artifact@v3
        with:
          name: solana-simulator-simulate-linux-x86_64
          path: bins
      - uses: actions/download-artifact@v3
        with:
          name: solana-simulator-get-program-data-linux-x86_64
          path: bins

      - name: Create Release
        uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: "bins/*"
          tag: ${{ env.RELEASE_VERSION }}
            
